### ISSUE TITLE
OpenCorporates  

### ISSUE THREAD

**Issue by charlesyoung** [Pzangeneh/uponto_mapping#2]
Consider using the OpenCorporates data to link data. 

Examples. 

[BP ](https://www.resourcecontracts.org/contract/ocds-591adf-7202085028)contract in the Ivory Coast
[BP ](https://opencorporates.com/companies?utf8=%E2%9C%93&q=BP+Exploration+Operating+Company+Limited&commit=Go&jurisdiction_code=&utf8=%E2%9C%93&controller=searches&action=search_companies&order=) OpenCorporates  data

**Comment by Pzangeneh** [comment]
Thanks Charles!
